export const FUNNY_LOADING_TEXTS = [
  "Bribing the dealer...",
  "Rigging the deck... I mean, shuffling!",
  "Hiding the extra Aces...",
  "Teaching the dealer how to count to 21...",
  "Rolling the dice... wait, wrong game.",
  "Shuffling... *drops cards*... picking them up...",
  "Kicking out the card counters...",
  "Stalling for dramatic effect...",
  "Downloading more luck...",
  "Telling the dealer we aren't playing Go Fish...",
  "Checking your sleeves for extra cards...",
  "Dealing from the bottom of the array...",
  "Consulting the RNG gods...",
  "Asking the boss if you are kicked out...",
  "Polishing the virtual floor...",
  "Trying to remember what a 'Jack' looks like...",
  "Waiting for the dealer to finish their coffee...",
  "Calling your bank to pre-approve the next bet...",
  "Adjusting the virtual lights...",
  "Asking the deck nicely to cooperate...",
  "Searching for the missing cards...",
  "Making sure the dealer had a good lunch...",
  "Counting chips just to be sure...",
  "Double-checking the house rules...",
  "Sending a signal to the invisible pit boss...",
  "Giving the deck a quick pep talk...",
  "Making sure your seat is lucky enough...",
  "Buffing the card edges for extra speed...",
  "Synchronizing with the deck...",
  "Checking if it's your lucky day yet..."
];