name: Build and deploy Node.js app to Azure Web App - blackjack-react

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: blackjack-react
        run: npm install

      - name: Build project
        working-directory: blackjack-react
        run: |
          echo "VITE_BLACKJACK_API_URL=blackjack-backend-eacdc5apakctgqer.canadaeast-01.azurewebsites.net" >> .env
          npm install
          npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A6F0800056164A2AAD5E1F3DE217358A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AAA8055A45854D4BA63B4A617496E7D2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FCB5D70DBEB84557B6CDE10F25A17480 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: blackjack-react
          slot-name: Production
          package: blackjack-react/dist
